name: tag
on:
  push:
    tags:
      # this is a glob, not a regexp
      - '[0-9]*'
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v2
        with:
          # need this to also fetch tags
          fetch-depth: 0

      - name: Build release tarball
        # run as root; current Ubuntu podman breaks user networking ("could not find slirp4netns")
        run: sudo PUBLISH_TAR=1 tests/run-apt

      - name: Create GitHub release
        uses: eloquent/github-release-action@v2
